export const SET_SEARCHED_RECIPES = 'SET_SEARCHED_RECIPES';
export const SET_SEARCHED_DETAILS = 'SET_SEARCHED_DETAILS';
export const ADD_RECIPE = 'ADD_RECIPE';
export const SET_LOADER = 'SET_LOADER';
export const SET_CASE_DETAILS = 'SET_CASE_DETAILS';
